version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x

  pre_build:
    commands:
      - echo "Changing to cicd directory"
      - cd cicd
      - echo "Making scripts executable"
      - chmod +x install-terraform.sh configure-named-profile.sh apply-terraform.sh
      - echo "Running install-terraform.sh"
      - ./install-terraform.sh
      - echo "Running configure-named-profile.sh"
      - ./configure-named-profile.sh

  build:
    commands:
      - echo "Running apply-terraform.sh"
      - ./apply-terraform.sh